/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        base: {
          950: "#08090c",
          900: "#0d0f14",
          850: "#12151c",
          800: "#171b24",
          700: "#232833",
          600: "#333a48",
          500: "#4a5262",
        },
        signal: {
          ok: "#3ddc97",
          warn: "#f5b942",
          crit: "#ff5c5c",
          idle: "#5b6478",
          info: "#5aa9ff",
        },
        "text-secondary": "#4a5262",
        "border-hairline": "#232833",
        "background": "#121316",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-primary-container": "#003d6c",
        "on-secondary-fixed": "#002112",
        "tertiary": "#f9bc45",
        "on-primary-fixed": "#001c37",
        "tertiary-fixed": "#ffdea8",
        "primary-container": "#5aa9ff",
        "on-surface-variant": "#c0c7d3",
        "on-tertiary-fixed-variant": "#5e4200",
        "secondary": "#42e09a",
        "surface-dim": "#121316",
        "inverse-surface": "#e3e2e6",
        "outline-variant": "#404751",
        "primary": "#a1c9ff",
        "on-error": "#690005",
        "primary-fixed": "#d2e4ff",
        "text-primary": "#ffffff",
        "on-secondary": "#003822",
        "on-secondary-container": "#00472c",
        "on-surface": "#e3e2e6",
        "surface-bright": "#38393d",
        "text-muted": "#333a48",
        "on-tertiary": "#422d00",
        "on-background": "#e3e2e6",
        "on-primary": "#00325a",
        "surface-elevated": "#0d0f14",
        "surface-container-low": "#1b1b1f",
        "surface-tint": "#a1c9ff",
        "tertiary-fixed-dim": "#f9bc45",
        "tertiary-container": "#d49c25",
        "on-tertiary-container": "#503700",
        "surface-container-high": "#292a2d",
        "surface-variant": "#343538",
        "signal-crit": "#ff5c5c",
        "surface": "#121316",
        "on-tertiary-fixed": "#271900",
        "secondary-container": "#00c07e",
        "on-primary-fixed-variant": "#004880",
        "surface-container": "#12151c",
        "on-secondary-fixed-variant": "#005233",
        "secondary-fixed": "#65fdb5",
        "secondary-fixed-dim": "#42e09a",
        "surface-container-lowest": "#0d0e11",
        "outline": "#8a919d",
        "surface-container-highest": "#343538",
        "inverse-primary": "#0060a7",
        "primary-fixed-dim": "#a1c9ff",
        "inverse-on-surface": "#2f3034",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "gutter": "16px",
        "margin-desktop": "24px",
        "panel-gap": "12px",
        "unit": "4px",
        "container-padding": "20px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "badge-mono": ["JetBrains Mono"],
        "display-lg": ["Inter"],
        "code-stat": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "body-base": ["Inter"],
        "code-data": ["JetBrains Mono"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["16px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "badge-mono": ["10px", {"lineHeight": "12px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.025em", "fontWeight": "800"}],
        "code-stat": ["24px", {"lineHeight": "24px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-caps": ["11px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-base": ["14px", {"lineHeight": "20px", "letterSpacing": "0", "fontWeight": "400"}],
        "code-data": ["12px", {"lineHeight": "16px", "letterSpacing": "0", "fontWeight": "500"}]
      },
      boxShadow: {
        glow: "0 0 0 1px rgba(255,255,255,0.04), 0 8px 24px -8px rgba(0,0,0,0.6)",
      },
    },
  },
  plugins: [],
};
